kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  podSubnet: "10.12.0.0/16"
  serviceSubnet: "10.13.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      dns:
        # TODO: Remove this after Kubernetes 1.35.
        # Reference: https://github.com/kubernetes/kubernetes/pull/132288
        imageTag: v1.12.2
