#!/usr/bin/env python

import sys
import argparse
import yaml

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('-m',  '--metadata', dest='metadata', help="Overwrite the resource's metadata with this value, may be any valid YAML")
  args = parser.parse_args()
  data = yaml.load(sys.stdin, Loader=yaml.Loader)
  if args.metadata:
    value = yaml.load(args.metadata, Loader=yaml.Loader)
    data['metadata'] = value
  print yaml.dump(data, indent=2, default_flow_style=False, Dumper=yaml.Dumper)